### ISSUE TITLE
To add a gene "Intelligence" 

### ISSUE THREAD

**Issue by Salt-is-leaving** [SophZoe/Genetic_Algorithm#44]
The options would to either make the agent move across the board not randomly but to look for the shortest route to the food source or alternatively to recognise and avoid the poisoned food.

**Comment by Jxshyz** [comment]
This gene allows agents to memorize poisonous foods

**Comment by julietteyek** [comment]
update move & consume method according to the intelligence-features;
agent shouldn't move around a poisonous food: just let the agent ignore poisonous food from the beginning.

(optional: the first intelligent generation only knows what food is poisonous when it has eaten one. From then on it avoids this particular food and "tells" the children, so that they also avoid all the poisonous food their parents "learned" to avoid.)
